cir_name = '100by100_with_decaps+inductance.cir'
netlist = open(cir_name, 'w')
netlist.write("""\
* This file is generated using a Python script.
* DO NOT EDIT THIS FILE MANUALLY. Your changes will be lost.
.title 100x100 grid of 1ohm (realistic) resistors + decaps
*
.tran 1ps 10ns
.measure tran yavg AVG i(Vin) from=2ns to=4ns
.plot i(Vin)
*
* resistance segment model:
.subckt Rseg 1 3
R1 1 2 0.583
L1 2 3 0.003n
C1 1 0 0.25e-12
C2 3 0 0.25e-12
.ends
""")

# maintain a total count of resistors, voltge sources, currnet sinks
# useful in naming
count_R = 0
count_dC = 0 # decap count
count_I = 0

#count_V = 0
decap = '2e-15'

no_x_nodes = 101
no_y_nodes = 101

# add the horizontal resistors
for k in xrange(1,no_x_nodes*(no_y_nodes-1)+2,no_x_nodes):
    for i in xrange(k,k+no_x_nodes-1):
        count_R = count_R + 1
        netlist.write("X" + str(count_R) + " " + str(i) + " " + str(i+1) + " " + "Rseg" + "\n")
        
        
# add the vertical resistors
for k in xrange(1,no_x_nodes*(no_y_nodes-2)+2,no_x_nodes):
    for i in xrange(k,k+no_x_nodes):
        count_R = count_R + 1
        netlist.write("X" + str(count_R) + " " + str(i) + " " + str(i+no_x_nodes) + " " + "Rseg" + "\n")
 
# add decapas to the internal nodes
for k in xrange(no_x_nodes+2,no_x_nodes*(no_y_nodes-2)+3,no_x_nodes):
    for i in xrange(k,k+no_x_nodes-2):
        count_dC = count_dC + 1
        netlist.write("C" + str(count_dC) + " " + str(i) + " " + "0" + " " + decap + "\n")
        
# add a 1V voltage source to the node 1
netlist.write("Vin 1 0 1.0" + "\n")

# we want to pulsate one current source
# we place the current source at the opposite node ie node (no_x_nodes*no_y_nodes)
# we use a PULSE current source
count_I = count_I + 1
netlist.write("I" + str(count_I) +  " " + str(no_x_nodes*no_y_nodes) + " " + "gnd_dummy" + " " + "PULSE(0uA 30uA 30ps 0 0 30ps 2n)" + "\n")

# add an "ammeter" to measure sink current
netlist.write("Vprobe gnd_dummy 0 DC 0.0" + "\n")

netlist.write(".end")
netlist.close()
